version: 2.1
orbs:
  cypress: cypress-io/cypress@1
executors:
  with-chrome:
    docker:
    - image: 'cypress/browsers:node14.16.0-chrome90-ff88'
workflows:
  build:
    jobs:
      - cypress/run:
          name: Chrome
          spec: cypress/integration/ui/*
          executor: with-chrome
          browser: chrome
          command: npm run chrome
          store_artifacts: true
          post-steps:
            - store_artifacts:
                path: mochawesome-report

